- defaults:
    link:
      create: true
      relink: true

- shell:
    - command: "command -v rustup || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile default"
      description: "Installs rustup and the latest rust toolchain (and cargo)."
    - command: "command -v starship || curl -sS https://starship.rs/install.sh | sh"
      description: "Installs starship if not already installed."
    - command: "[ -d ~/.asdf ] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1"
      description: "Clones asdf if not there already."
    - command: "command -v poetry || "

- ifmacos:
    - brew:
        - git
        - coreutils
        - curl
        - fzf
        - bat
        - poetry

- ifdebian:
    - apt:
        - git
        - net-tools
        - curl

- clean:
    ~/:
    ~/.config:
      recursive: true

- asdf:
    - plugin: python
      global: latest
      versions:
        - latest
    - plugin: nodejs
      global: latest
      versions:
        - latest
    - plugin: golang
      url: https://github.com/asdf-community/asdf-golang.git
      global: latest
      versions:
        - latest

- create:
    ~/.ssh:
      mode: 0700

- link:
    ~/.zshrc:
    ~/.dotfiles: ""
    ~/.config/starship.toml: config/starship.toml
    ~/.ssh/config: config/.ssh/config
    ~/.gitconfig: config/.gitconfig
