- defaults:
    link:
      create: true
      relink: true

- install-brew: true

- brew:
    - git
    - asdf
    - fzf
    - bat
    - poetry

- clean:
    ~/:
    ~/.config:
      recursive: true

- asdf:
    - plugin: python
      global: latest
      versions:
        - latest
    - plugin: nodejs
      global: latest
      versions:
        - latest

- create:
    ~/.ssh:
      mode: 0700

- link:
    ~/.zshrc:
    ~/.zshenv:
    ~/.zimrc:
    ~/.p10k.zsh:
    ~/.dotfiles: ""
    ~/.ssh/config: config/.ssh/config
    ~/.gitconfig: config/.gitconfig
