#!/usr/bin/env bash

set -e

CONFIG=".install.conf.yaml"
DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

python3 "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
    --plugin-dir .dotbot-plugins/dotbot-brew \
    --plugin-dir .dotbot-plugins/dotbot-asdf \
    --plugin-dir .dotbot-plugins/dotbot-ifplatform \
    --plugin-dir .dotbot-plugins/dotbot-apt/apt.py \
    -c "${CONFIG}" "${@}"
