#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.14"
# ///

import json
import re
import subprocess
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parent.parent
CACHE = REPOSITORY / ".just-hosts.just"


def nix_eval(installable: str, description: str) -> list[str]:
    result = subprocess.run(
        ["nix", "eval", "--json", installable, "--apply", "builtins.attrNames"],
        cwd=REPOSITORY,
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    value = json.loads(result.stdout)
    assert isinstance(value, list) and all(isinstance(item, str) for item in value), (
        f"expected {description} to evaluate to a list of strings"
    )
    return value


def main() -> None:
    hosts = nix_eval(".#darwinConfigurations", "hostnames")
    host_users: dict[str, list[str]] = {}

    for host in hosts:
        host_attr = json.dumps(host)
        host_users[host] = nix_eval(
            f".#darwinConfigurations.{host_attr}.config.home-manager.users",
            f"usernames for {host}",
        )

    host_pattern = "|".join(re.escape(host) for host in hosts)
    host_users_json = json.dumps(host_users, separators=(",", ":"))
    contents = "\n".join(
        [
            "# Generated by `just update-hosts`; do not edit manually.",
            f"valid_hosts := {json.dumps(host_pattern)}",
            f"host_users := {json.dumps(host_users_json)}",
            "",
        ]
    )

    CACHE.write_text(contents, encoding="utf-8")


if __name__ == "__main__":
    main()
