#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.14"
# ///

import json
import re
import subprocess
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parent.parent
CACHE = REPOSITORY / ".just-hosts.just"


def nix_eval(installable: str, description: str) -> list[str]:
    result = subprocess.run(
        ["nix", "eval", "--json", installable, "--apply", "builtins.attrNames"],
        cwd=REPOSITORY,
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    value = json.loads(result.stdout)
    assert isinstance(value, list) and all(isinstance(item, str) for item in value), (
        f"expected {description} to evaluate to a list of strings"
    )
    return value


def main() -> None:
    configuration_types = {
        "darwin": "darwinConfigurations",
        "nixos": "nixosConfigurations",
    }
    hosts_by_type = {
        config_type: nix_eval(f".#{flake_attr}", f"{config_type} hostnames")
        for config_type, flake_attr in configuration_types.items()
    }
    hosts = sorted(host for typed_hosts in hosts_by_type.values() for host in typed_hosts)

    if len(hosts) != len(set(hosts)):
        raise ValueError("hostnames must be unique across Darwin and NixOS configurations")

    host_users: dict[str, list[str]] = {}

    for config_type, typed_hosts in hosts_by_type.items():
        flake_attr = configuration_types[config_type]
        for host in typed_hosts:
            host_attr = json.dumps(host)
            host_users[host] = nix_eval(
                f".#{flake_attr}.{host_attr}.config.home-manager.users",
                f"usernames for {host}",
            )

    host_pattern = "|".join(re.escape(host) for host in hosts)
    type_patterns = {
        config_type: "|".join(re.escape(host) for host in sorted(typed_hosts))
        for config_type, typed_hosts in hosts_by_type.items()
    }
    lima_nixos_prefix = "lima-nixos-"
    lima_nixos_hosts = sorted(
        host.removeprefix(lima_nixos_prefix)
        for host in hosts_by_type["nixos"]
        if host.startswith(lima_nixos_prefix)
    )
    lima_nixos_host_pattern = "|".join(re.escape(host) for host in lima_nixos_hosts)
    host_users_json = json.dumps(host_users, separators=(",", ":"))
    contents = "\n".join(
        [
            "# Generated by `just update-hosts`; do not edit manually.",
            f"valid_hosts := {json.dumps(host_pattern)}",
            f"darwin_hosts := {json.dumps(type_patterns['darwin'])}",
            f"nixos_hosts := {json.dumps(type_patterns['nixos'])}",
            f"lima_nixos_hosts := {json.dumps(lima_nixos_host_pattern)}",
            f"host_users := {json.dumps(host_users_json)}",
            "",
        ]
    )

    CACHE.write_text(contents, encoding="utf-8")


if __name__ == "__main__":
    main()
