github_token: ENC[AES256_GCM,data:/LL+zCW/a9Ksmj5QKSfYrzaw4e4CIM/ViGK0/eWC3/VZjXYJ8bO/Aw==,iv:3fOZMVV9w5IdGa/oMEDqaD8D1H3KCEQLJkGntDDXY10=,tag:rUyOhljFqCYKk1W+leI5eA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISkZUdG5DS3A2aU1URmJM
            K2NjRU0wN1gvQ3ZSNFJ0THFMOUFzTXB1VlhBCklxNWJGN21RMTJudWRMT3ZrN0hX
            Y3Q3NGZTcEJwVlB5NUpBc1g3Z1NvYlkKLS0tIFM2TWp6RVRxd01CLzF1bkdRUHFz
            M0swZDVWeUVPVlhVdHB6bXVnMEdJMWcKqXa8DJHyjYf4JoUxdu/z0zjYsZkSpi2G
            1q5W5GPm/QhxypilHADDvYdc95SPKNPtxqvzQ4KuRP8xIB7ieLt4RQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10uqazprqk5jfkvh2snlc8yavmacmzhlsxhn0tdpxa5j9ptf97q4sejxehq
    lastmodified: "2026-08-26T03:36:54Z"
    mac: ENC[AES256_GCM,data:4vdGlSTl9eQ0YTlj+9WAHZ7MamhYKK7/hGvlbpR4/Mz3ZUs+rdwfcm3gJepBuRveuUeXX4wf1C5OaPLZLOmHOhQ4/S20g7KchyHbxsjIB3g1ekZMbgQqOpBt6tGaQp9eRq0TsV9xfrdTkPzqPgYLtFW/DAE85jvfj6yuMJvKhrg=,iv:mK667jE6mADNB8h80KMtzbsZi3ive8zlPtV4qMfN3lE=,tag:KfbrTQqWeRq9gMTV0fhvog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
