github_token: ENC[AES256_GCM,data:/LL+zCW/a9Ksmj5QKSfYrzaw4e4CIM/ViGK0/eWC3/VZjXYJ8bO/Aw==,iv:3fOZMVV9w5IdGa/oMEDqaD8D1H3KCEQLJkGntDDXY10=,tag:rUyOhljFqCYKk1W+leI5eA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRCtweHk1R2VONDZvM0tU
            UEUvTFhqUUk0VWFjU1k1YkVSOTUzWXA0SFc4CjI0QXNFZHNvMmNqRDk0WE5GSStz
            YXNNUVB5Q2k5UDBQdzNWYWI4SWdzdGcKLS0tIGF6R0p5V21xNFlnSnlJL3FpQkJX
            RGRlZllhcGp2bHpMamhzYk53ci9sU0UKgqkwlrMvCZMVYJF3UTWn28OGsu8N6h1y
            EZaWjpJgqB4jw403xqy5CnRZD8dwHDxVCVZEp2kJC8uzFrlJdn9vyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q4xrt58ufwd422kcefqumqmtnf4lc344cytdejzfm86vlm4aavfq9tve68
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgVGI2Skx3IEJJN1V4bVJK
            dzROTnJ4L3YwaFBvMFZBTVZPVFZUY0t1ZXl2OTNjVGJsOVdWdXlCbEx1eWUzb01Q
            OEhxU1oyR2tSa28rU2RGNC94ZVUwODFEZStBYVhhYwpuSS9ZVGRJbTFtZnpuZjI1
            b2hSalF6dFhkZnlrbTlpOGJaV0Q0a25ud0J3Ci0tLSAvUnNrTGhMODNzc215dlg3
            K2twWis3Z3BxWnZoWWhWZW5YNitHVjhERDJrCjcuqfg85R/m/k+HKAY8ZpHQQFgv
            6kRelmsr3ONIr3FNjAPcRSQYyh+Uj3QMM8o1ISAEVPkxdFJaW/k3gn9XbdY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1qdx0qngaq4yel29a38p527fvlpnsdku2u6zekpnn3g3qtmjuqchh7amzegf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRVNyWHlUdnBaa1I3TlM4
            R0MyditVS0x2S2pNbVhEelFUYjRzSFNvZDAwCkN2RmpZcDY2azRoTXhERG9uMUZU
            VDBWaWJHS29PMFBqZFlOMWlXQVVHNHcKLS0tIHVuZjlrSmozZEdPMEJ2MWE0V2Yw
            dU5sZFVoYVpWRkxQMzZycE1mcUNhd1kKCHiu3O3/DbsBUQgS+UKgMIR/eKbnJ4fd
            mhVTmbYIuEddQKHI5FSZgn3NLVWADghaOPQ+Z6rUHoKpHP21bGUwJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10uqazprqk5jfkvh2snlc8yavmacmzhlsxhn0tdpxa5j9ptf97q4sejxehq
    lastmodified: "2026-08-26T03:36:54Z"
    mac: ENC[AES256_GCM,data:4vdGlSTl9eQ0YTlj+9WAHZ7MamhYKK7/hGvlbpR4/Mz3ZUs+rdwfcm3gJepBuRveuUeXX4wf1C5OaPLZLOmHOhQ4/S20g7KchyHbxsjIB3g1ekZMbgQqOpBt6tGaQp9eRq0TsV9xfrdTkPzqPgYLtFW/DAE85jvfj6yuMJvKhrg=,iv:mK667jE6mADNB8h80KMtzbsZi3ive8zlPtV4qMfN3lE=,tag:KfbrTQqWeRq9gMTV0fhvog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
