github_token: ENC[AES256_GCM,data:/LL+zCW/a9Ksmj5QKSfYrzaw4e4CIM/ViGK0/eWC3/VZjXYJ8bO/Aw==,iv:3fOZMVV9w5IdGa/oMEDqaD8D1H3KCEQLJkGntDDXY10=,tag:rUyOhljFqCYKk1W+leI5eA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dldLa0s1NXo4RFlQZGVn
            R1BDaGcxR0hWcGFkYmsxMWJmSFExck9iOGdrCmxZQ1k1em54WWF2ZFJUbTY4Sldn
            dk1KZkNscVQrallld2VzWHlYSWttZWMKLS0tIGYxTGlXSEROUllUd0lGcDE5YmRk
            QlhwSlVVQ2tzY1dBYWk5TXZzK3pZdGcK3LXRrHBsfHzjWaPmNRUrQUAS5Jl1LFwo
            rWukFAXCOlBJQI9zMU8daKQ3mabh5MD+MMHyGYIQ1vfJwer+ATfogQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q4xrt58ufwd422kcefqumqmtnf4lc344cytdejzfm86vlm4aavfq9tve68
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZ3pFTzN6MXQyUWZYcEFC
            RnUrOGdOajdaSkJGSFJrYllFWnB6dU01VW0wCmV6ZFBBSlpnNmdrTkUwQVFLc0ZQ
            VUppYkR6ald6dERlK2FSZHRTSUVWeHMKLS0tIHBSQXU0SFNmWmNmWDBkU2prMEdt
            SXQ1cXFIY0hNdzJYUngwWHZ1UWFOTTQKQgWUQZ4/CBVvx1XFVblzRdPEIB4eMq4E
            p3jimSGtQi6LeNmGcqMgeK2xpsZkc1t0uOE6VjRRptNd2aex5mhDcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10uqazprqk5jfkvh2snlc8yavmacmzhlsxhn0tdpxa5j9ptf97q4sejxehq
    lastmodified: "2026-08-26T03:36:54Z"
    mac: ENC[AES256_GCM,data:4vdGlSTl9eQ0YTlj+9WAHZ7MamhYKK7/hGvlbpR4/Mz3ZUs+rdwfcm3gJepBuRveuUeXX4wf1C5OaPLZLOmHOhQ4/S20g7KchyHbxsjIB3g1ekZMbgQqOpBt6tGaQp9eRq0TsV9xfrdTkPzqPgYLtFW/DAE85jvfj6yuMJvKhrg=,iv:mK667jE6mADNB8h80KMtzbsZi3ive8zlPtV4qMfN3lE=,tag:KfbrTQqWeRq9gMTV0fhvog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
